export const AUTH_CONTENT = {
  login: {
    title: "Welcome Back",
    description: "Sign in to your account to continue",
    image: "/img/login.png",
    alt: "Login Illustration",
    buttonText: "Login",
    footerText: "Don't have an account?",
    footerLinkText: "Sign up here",
    footerLinkHref: "/register",
    forgotPasswordText: "Forgot Password?",
    forgotPasswordHref: "/forgot-password",
  },
  register: {
    title: "Create Account",
    description: "Fill in your details to get started",
    image: "/img/registration.png",
    alt: "Registration Illustration",
    buttonText: "Register",
    footerText: "Already have an account?",
    footerLinkText: "Sign in",
    footerLinkHref: "/login",
  },
  signup: {
    title: "Sign Up",
    description: "Create a new account to get started",
    image: "/img/auth.png",
    alt: "Sign Up Illustration",
    buttonText: "Sign Up",
    footerText: "Already have an account?",
    footerLinkText: "Sign in",
    footerLinkHref: "/login",
  },
  forgotPassword: {
    title: "Forgot Password",
    description: "Enter your email and we'll send you a reset link",
    image: "/img/forgot-password.png",
    alt: "Forgot Password Illustration",
    buttonText: "Send Link",
    footerText: "Remember your password?",
    footerLinkText: "Sign in",
    footerLinkHref: "/login",
  },
  resetPassword: {
    title: "Reset Password",
    description: "Choose a new secure password for your account",
    image: "/img/reset-password.png",
    alt: "Reset Password Illustration",
    buttonText: "Reset Password",
    footerText: "Back to",
    footerLinkText: "Sign in",
    footerLinkHref: "/login",
  },
};
